@startuml components
!pragma layout smetana

package Lamagraph.Compiler {
    component Syntax
    component Parser
    component Typechecker
    component Core
    component LmlToCore
    component Eval
}

Eval --> Core
LmlToCore --> Typechecker
LmlToCore --> Core
Typechecker --> Parser
Typechecker --> Syntax
Parser -> Syntax

package Lamagraph.Nets {
    component Reduction
    component Processing
    component Types
    component CoreToNet
}

Reduction --> Types
Processing --> Types
CoreToNet -> Core
CoreToNet -> Types
Processing --[hidden]> Core

@enduml
